### ISSUE TITLE
Error while running with sitespeed

### ISSUE THREAD

**Issue by softwareklinic** [sitespeedio/plugin-gpsi#10] opened 2019-04-25 16:55 UTC
desktop failed, reason: connect EINVAL 0.0.0.37:443 - Local (0.0.0.0:0)
    at ClientRequest.<anonymous> (/sitespeed.io/gpsi/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-04-25 16:26:43] INFO: Running tests using Chrome - 3 iteration

**Comment by soulgalore** [comment] 2019-04-25 18:28
Seems to be a problem with GPSI, could it be a non valid certificate?

**Comment by soulgalore** [comment] 2021-04-14 04:06
I haven't been able to reproduce + upstream so I'm closing.

**Closed by soulgalore** 2021-04-14 04:06 UTC
Labels: upstream
